-- Group name:   T01-Group07
-- Group member: Lim Yu-Shan, Ng Chen Ting, Yang Thong Chen

SET ECHO ON
SPOOL monh_schema_output.txt

-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2022-09-13 19:37:37 SGT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

DROP TABLE combo CASCADE CONSTRAINTS;

DROP TABLE customer CASCADE CONSTRAINTS;

DROP TABLE employee CASCADE CONSTRAINTS;

DROP TABLE job CASCADE CONSTRAINTS;

DROP TABLE quote CASCADE CONSTRAINTS;

DROP TABLE quote_combo CASCADE CONSTRAINTS;

DROP TABLE quote_purpose CASCADE CONSTRAINTS;

DROP TABLE trailer CASCADE CONSTRAINTS;

DROP TABLE trailer_class CASCADE CONSTRAINTS;

DROP TABLE trailer_type CASCADE CONSTRAINTS;

DROP TABLE truck CASCADE CONSTRAINTS;

DROP TABLE truck_class CASCADE CONSTRAINTS;

DROP TABLE truck_type CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE combo (
    combo_code          VARCHAR2(3) NOT NULL,
    quote_purpose_no    NUMBER(4) NOT NULL,
    truck_vehicle_id_no CHAR(17) NOT NULL,
    trailer_id_code     CHAR(5) NOT NULL
);

COMMENT ON COLUMN combo.truck_vehicle_id_no IS
    'Truck''s Identification Number (VIN)';

COMMENT ON COLUMN combo.trailer_id_code IS
    'Trailer ID code.';

ALTER TABLE combo ADD CONSTRAINT combo_pk PRIMARY KEY ( combo_code );

CREATE TABLE customer (
    cust_no        NUMBER(5) NOT NULL,
    cust_fname     VARCHAR2(20) NOT NULL,
    cust_gname     VARCHAR2(20) NOT NULL,
    cust_bname     VARCHAR2(20),
    cust_address   VARCHAR2(50) NOT NULL,
    cust_contactno VARCHAR2(15) NOT NULL
);

COMMENT ON COLUMN customer.cust_no IS
    'Customer number.';

COMMENT ON COLUMN customer.cust_fname IS
    'Customer family name.';

COMMENT ON COLUMN customer.cust_gname IS
    'Customer given name.';

COMMENT ON COLUMN customer.cust_bname IS
    'Customer business name.';

COMMENT ON COLUMN customer.cust_address IS
    'Customer address.';

COMMENT ON COLUMN customer.cust_contactno IS
    'Customer contact number.';

ALTER TABLE customer ADD CONSTRAINT customer_pk PRIMARY KEY ( cust_no );

CREATE TABLE employee (
    emp_no         NUMBER(3) NOT NULL,
    emp_fname      VARCHAR2(20) NOT NULL,
    emp_gname      VARCHAR2(20) NOT NULL,
    emp_contactno  VARCHAR2(15) NOT NULL,
    emp_taxfileno  NUMBER(9) NOT NULL,
    emp_salary     NUMBER(6, 2) NOT NULL,
    emp_role       VARCHAR2(20),
    emp_licence_no NUMBER(11),
    mgr_no         NUMBER(3),
    truck_class_no NUMBER(1)
);

COMMENT ON COLUMN employee.emp_no IS
    'Employee number.';

COMMENT ON COLUMN employee.emp_fname IS
    'Employee first name.';

COMMENT ON COLUMN employee.emp_gname IS
    'Employee given name.';

COMMENT ON COLUMN employee.emp_contactno IS
    'Employee contact number.';

COMMENT ON COLUMN employee.emp_taxfileno IS
    'Employee tax file number.';

COMMENT ON COLUMN employee.emp_salary IS
    'Employee salaray.';

COMMENT ON COLUMN employee.emp_role IS
    'Employee role.';

COMMENT ON COLUMN employee.emp_licence_no IS
    'Employee licence number (for drivers).';

COMMENT ON COLUMN employee.mgr_no IS
    'Employee number.';

COMMENT ON COLUMN employee.truck_class_no IS
    'Truck class number.';

ALTER TABLE employee ADD CONSTRAINT employee_pk PRIMARY KEY ( emp_no );

CREATE TABLE job (
    job_no                     NUMBER(4) NOT NULL,
    job_pickup_datetime        DATE NOT NULL,
    job_intended_drop_datetime DATE NOT NULL,
    job_actual_drop_datetime   DATE NOT NULL,
    job_has_paid               CHAR(1) NOT NULL,
    job_cost                   NUMBER(4, 2),
    job_paid_date              DATE NOT NULL,
    quote_no                   NUMBER(4) NOT NULL,
    truck_vehicle_id_no        CHAR(17) NOT NULL,
    trailer_id_code            CHAR(5) NOT NULL,
    job_clerk_emp_no           NUMBER(3) NOT NULL,
    job_driver_emp_no          NUMBER(3) NOT NULL,
    job_mechanic_emp_no        NUMBER(3) NOT NULL,
    combo_code                 VARCHAR2(3) NOT NULL
);

ALTER TABLE job
    ADD CONSTRAINT chk_job_has_paid CHECK ( job_has_paid IN ( 'F', 'T' ) );

COMMENT ON COLUMN job.job_no IS
    'Job number.';

COMMENT ON COLUMN job.job_pickup_datetime IS
    'Job pickup date and time.';

COMMENT ON COLUMN job.job_intended_drop_datetime IS
    'Job intended drop off date and time.';

COMMENT ON COLUMN job.job_actual_drop_datetime IS
    'Job actual drop off date and time.';

COMMENT ON COLUMN job.job_has_paid IS
    'Whether customer has paid for the job: T is yes, F is no.';

COMMENT ON COLUMN job.job_cost IS
    'Job cost (if different from quote cost).';

COMMENT ON COLUMN job.job_paid_date IS
    'Date of job payment.';

COMMENT ON COLUMN job.quote_no IS
    'Quote number.';

COMMENT ON COLUMN job.truck_vehicle_id_no IS
    'Truck''s Identification Number (VIN)';

COMMENT ON COLUMN job.job_clerk_emp_no IS
    'Employee number.';

COMMENT ON COLUMN job.job_driver_emp_no IS
    'Employee number.';

COMMENT ON COLUMN job.job_mechanic_emp_no IS
    'Employee number.';

CREATE UNIQUE INDEX job__idx ON
    job (
        quote_no
    ASC );

ALTER TABLE job ADD CONSTRAINT job_pk PRIMARY KEY ( job_no );

CREATE TABLE quote (
    quote_no               NUMBER(4) NOT NULL,
    quote_book_startdate   DATE NOT NULL,
    quote_pickup_location  VARCHAR2(50) NOT NULL,
    quote_dropoff_location VARCHAR2(50) NOT NULL,
    quote_cost             NUMBER(4, 2) NOT NULL,
    quote_prep_date        DATE NOT NULL,
    quote_no_of_days       NUMBER(2) NOT NULL,
    cust_no                NUMBER(5) NOT NULL,
    quote_purpose_no       NUMBER(4) NOT NULL
);

COMMENT ON COLUMN quote.quote_no IS
    'Quote number.';

COMMENT ON COLUMN quote.quote_book_startdate IS
    'Booking start date on quote.';

COMMENT ON COLUMN quote.quote_pickup_location IS
    'Pickup location on quote.';

COMMENT ON COLUMN quote.quote_dropoff_location IS
    'Drop off location on quote.';

COMMENT ON COLUMN quote.quote_cost IS
    'Quote cost.';

COMMENT ON COLUMN quote.quote_prep_date IS
    'Quote preparation date.';

COMMENT ON COLUMN quote.quote_no_of_days IS
    'Number of days required.';

COMMENT ON COLUMN quote.cust_no IS
    'Customer number.';

COMMENT ON COLUMN quote.quote_purpose_no IS
    'Quote purpose number.';

ALTER TABLE quote ADD CONSTRAINT quote_pk PRIMARY KEY ( quote_no );

CREATE TABLE quote_combo (
    quote_combo_id   NUMBER(4) NOT NULL,
    combo_code       VARCHAR2(3) NOT NULL,
    quote_purpose_no NUMBER(4) NOT NULL
);

COMMENT ON COLUMN quote_combo.quote_combo_id IS
    'Combo and quote purpose number (surrogate key dervied from combo_code and quote_purpoes_no).';

COMMENT ON COLUMN quote_combo.quote_purpose_no IS
    'Quote purpose number.';

ALTER TABLE quote_combo ADD CONSTRAINT quote_combo_pk PRIMARY KEY ( quote_combo_id );

ALTER TABLE quote_combo ADD CONSTRAINT quote_combo_nk UNIQUE ( combo_code,
                                                               quote_purpose_no );

CREATE TABLE quote_purpose (
    quote_purpose_no   NUMBER(4) NOT NULL,
    quote_purpose_desc VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN quote_purpose.quote_purpose_no IS
    'Quote purpose number.';

COMMENT ON COLUMN quote_purpose.quote_purpose_desc IS
    'Quote purpose description.';

ALTER TABLE quote_purpose ADD CONSTRAINT quote_purpose_pk PRIMARY KEY ( quote_purpose_no );

CREATE TABLE trailer (
    trailer_id_code           CHAR(5) NOT NULL,
    trailer_purchase_date     DATE NOT NULL,
    trailer_purchase_cost     NUMBER(6, 2) NOT NULL,
    trailer_type_manufacturer VARCHAR2(20) NOT NULL,
    trailer_type_model        VARCHAR2(20) NOT NULL,
    trailer_type_no           NUMBER(3) NOT NULL
);

COMMENT ON COLUMN trailer.trailer_id_code IS
    'Trailer ID code.';

COMMENT ON COLUMN trailer.trailer_purchase_date IS
    'Trailer purchase date.';

COMMENT ON COLUMN trailer.trailer_purchase_cost IS
    'Trailer purchase cost.';

COMMENT ON COLUMN trailer.trailer_type_no IS
    'Trailer type number (surrogate key derived from trailer_type_manufacturer and trailer_type_model).';

ALTER TABLE trailer ADD CONSTRAINT trailer_pk PRIMARY KEY ( trailer_id_code );

CREATE TABLE trailer_class (
    trailer_class_no              VARCHAR2(3) NOT NULL,
    trailer_class_daily_hire_rate NUMBER(3, 2) NOT NULL
);

COMMENT ON COLUMN trailer_class.trailer_class_no IS
    'Trailer class number.';

COMMENT ON COLUMN trailer_class.trailer_class_daily_hire_rate IS
    'Daily hire rate of trailer class.';

ALTER TABLE trailer_class ADD CONSTRAINT trailer_class_pk PRIMARY KEY ( trailer_class_no );

CREATE TABLE trailer_type (
    trailer_type_manufacturer VARCHAR2(20) NOT NULL,
    trailer_type_model        VARCHAR2(20) NOT NULL,
    trailer_load_capacity     NUMBER(5) NOT NULL,
    trailer_length            NUMBER(2, 1) NOT NULL,
    trailer_class_no          VARCHAR2(3) NOT NULL,
    trailer_type_no           NUMBER(3) NOT NULL,
    trailer_width             NUMBER(1, 2) NOT NULL
);

COMMENT ON COLUMN trailer_type.trailer_type_manufacturer IS
    'Trailer type manufacturer.';

COMMENT ON COLUMN trailer_type.trailer_type_model IS
    'Trailer type model.';

COMMENT ON COLUMN trailer_type.trailer_load_capacity IS
    'Trailer type''s load capacity.';

COMMENT ON COLUMN trailer_type.trailer_length IS
    'Trailer length.';

COMMENT ON COLUMN trailer_type.trailer_class_no IS
    'Trailer class number.';

COMMENT ON COLUMN trailer_type.trailer_type_no IS
    'Trailer type number (surrogate key derived from trailer_type_manufacturer and trailer_type_model).';

COMMENT ON COLUMN trailer_type.trailer_width IS
    'Trailer width.';

ALTER TABLE trailer_type ADD CONSTRAINT trailer_type_pk PRIMARY KEY ( trailer_type_no );

ALTER TABLE trailer_type ADD CONSTRAINT trailer_type_nk UNIQUE ( trailer_type_manufacturer,
                                                                 trailer_type_model );

CREATE TABLE truck (
    truck_vehicle_id_no  CHAR(17) NOT NULL,
    truck_vehicle_reg_no CHAR(9) NOT NULL,
    truck_km_travelled   NUMBER(5) NOT NULL,
    truck_km_reading     NUMBER(5),
    truck_purchase_date  DATE NOT NULL,
    truck_purchase_cost  NUMBER(8, 2) NOT NULL,
    truck_type_make      VARCHAR2(20) NOT NULL,
    truck_type_model     VARCHAR2(20) NOT NULL,
    truck_type_no        NUMBER(3) NOT NULL
);

COMMENT ON COLUMN truck.truck_vehicle_id_no IS
    'Truck''s Identification Number (VIN)';

COMMENT ON COLUMN truck.truck_vehicle_reg_no IS
    'Truck''s Registration Number';

COMMENT ON COLUMN truck.truck_km_travelled IS
    'Number of kilometers the truck travelled';

COMMENT ON COLUMN truck.truck_km_reading IS
    'Truck''s kilometer reading of the last service ';

COMMENT ON COLUMN truck.truck_purchase_date IS
    'The date the truck was purchased';

COMMENT ON COLUMN truck.truck_purchase_cost IS
    'The purchase cost of the truck';

COMMENT ON COLUMN truck.truck_type_no IS
    'Truck type number (surrogate key derived from truck_type_make and truck_type_model).';

ALTER TABLE truck ADD CONSTRAINT truck_pk PRIMARY KEY ( truck_vehicle_id_no );

CREATE TABLE truck_class (
    truck_class_no               NUMBER(1) NOT NULL,
    truck_class_driver_hire_rate NUMBER(3, 2) NOT NULL,
    truck_class_daily_hire_rate  NUMBER(3, 2) NOT NULL
);

COMMENT ON COLUMN truck_class.truck_class_no IS
    'Truck class number.';

COMMENT ON COLUMN truck_class.truck_class_driver_hire_rate IS
    'Driver hire rate of truck class.';

COMMENT ON COLUMN truck_class.truck_class_daily_hire_rate IS
    'Daily hire rate of truck class.';

ALTER TABLE truck_class ADD CONSTRAINT truck_class_pk PRIMARY KEY ( truck_class_no );

CREATE TABLE truck_type (
    truck_type_make  VARCHAR2(20) NOT NULL,
    truck_type_model VARCHAR2(20) NOT NULL,
    truck_class_no   NUMBER(1) NOT NULL,
    truck_type_no    NUMBER(3) NOT NULL
);

COMMENT ON COLUMN truck_type.truck_type_make IS
    'Make of truck type.';

COMMENT ON COLUMN truck_type.truck_type_model IS
    'Model of truck type.';

COMMENT ON COLUMN truck_type.truck_class_no IS
    'Truck class number.';

COMMENT ON COLUMN truck_type.truck_type_no IS
    'Truck type number (surrogate key derived from truck_type_make and truck_type_model).';

ALTER TABLE truck_type ADD CONSTRAINT truck_type_pk PRIMARY KEY ( truck_type_no );

ALTER TABLE truck_type ADD CONSTRAINT truck_type_nk UNIQUE ( truck_type_make,
                                                             truck_type_model );

ALTER TABLE quote_combo
    ADD CONSTRAINT combo_quote_combo FOREIGN KEY ( combo_code )
        REFERENCES combo ( combo_code );

ALTER TABLE combo
    ADD CONSTRAINT combo_trailer FOREIGN KEY ( trailer_id_code )
        REFERENCES trailer ( trailer_id_code );

ALTER TABLE combo
    ADD CONSTRAINT combo_truck FOREIGN KEY ( truck_vehicle_id_no )
        REFERENCES truck ( truck_vehicle_id_no );

ALTER TABLE employee
    ADD CONSTRAINT employee_manager FOREIGN KEY ( mgr_no )
        REFERENCES employee ( emp_no );

ALTER TABLE employee
    ADD CONSTRAINT employee_truck_class FOREIGN KEY ( truck_class_no )
        REFERENCES truck_class ( truck_class_no );

ALTER TABLE job
    ADD CONSTRAINT job_employee_clerk FOREIGN KEY ( job_clerk_emp_no )
        REFERENCES employee ( emp_no );

ALTER TABLE job
    ADD CONSTRAINT job_employee_driver FOREIGN KEY ( job_driver_emp_no )
        REFERENCES employee ( emp_no );

ALTER TABLE job
    ADD CONSTRAINT job_employee_mechanic FOREIGN KEY ( job_mechanic_emp_no )
        REFERENCES employee ( emp_no );

ALTER TABLE job
    ADD CONSTRAINT job_quote FOREIGN KEY ( quote_no )
        REFERENCES quote ( quote_no );

ALTER TABLE quote
    ADD CONSTRAINT quote_customer FOREIGN KEY ( cust_no )
        REFERENCES customer ( cust_no );

ALTER TABLE combo
    ADD CONSTRAINT quote_purpose_combo FOREIGN KEY ( quote_purpose_no )
        REFERENCES quote_purpose ( quote_purpose_no );

ALTER TABLE quote_combo
    ADD CONSTRAINT quote_purpose_quote_combo FOREIGN KEY ( quote_purpose_no )
        REFERENCES quote_purpose ( quote_purpose_no );

ALTER TABLE quote
    ADD CONSTRAINT quote_quote_purpose FOREIGN KEY ( quote_purpose_no )
        REFERENCES quote_purpose ( quote_purpose_no );

ALTER TABLE job
    ADD CONSTRAINT relation_28 FOREIGN KEY ( combo_code )
        REFERENCES combo ( combo_code );

ALTER TABLE job
    ADD CONSTRAINT trailer_job FOREIGN KEY ( trailer_id_code )
        REFERENCES trailer ( trailer_id_code );

ALTER TABLE trailer
    ADD CONSTRAINT trailer_trailer_type FOREIGN KEY ( trailer_type_no )
        REFERENCES trailer_type ( trailer_type_no );

ALTER TABLE trailer_type
    ADD CONSTRAINT trailer_type_trailer_class FOREIGN KEY ( trailer_class_no )
        REFERENCES trailer_class ( trailer_class_no );

ALTER TABLE job
    ADD CONSTRAINT truck_job FOREIGN KEY ( truck_vehicle_id_no )
        REFERENCES truck ( truck_vehicle_id_no );

ALTER TABLE truck
    ADD CONSTRAINT truck_truck_type FOREIGN KEY ( truck_type_no )
        REFERENCES truck_type ( truck_type_no );

ALTER TABLE truck_type
    ADD CONSTRAINT truck_type_truck_class FOREIGN KEY ( truck_class_no )
        REFERENCES truck_class ( truck_class_no );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            13
-- CREATE INDEX                             1
-- ALTER TABLE                             37
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

SPOOL OFF
SET ECHO OFF
